## Script de validación de modelo
### Se obtiene predicción de precio con data de junio como data de validación, usando el mejor modelo obtenido en TFM_Airbnb.ipynb

Para este script son necesarios los siguientes ficheros:


1.   requirements.txt
2.   FuncionesTFM.py
3.   Pipeline_limpieza_data.py
4.   geo_barcelona.geojson
5.   modelo_xgb.json
6.   airbnb_junio.csv

Nota: Este script fue realizado en Colab por lo que el path de lectura de ficheros incia en  "/content/", se recomienda verificar el path de ubicación si se trabaja en local.

In [1]:
# Instalar requirements con su versión
!pip install -r "/content/requirements.txt"

Requirement already satisfied: fastapi==0.141.1 in /usr/local/lib/python3.13/dist-packages (from -r /content/requirements.txt (line 1)) (0.141.1)
Requirement already satisfied: Flask==3.1.3 in /usr/local/lib/python3.13/dist-packages (from -r /content/requirements.txt (line 2)) (3.1.3)
Requirement already satisfied: geopandas==1.1.4 in /usr/local/lib/python3.13/dist-packages (from -r /content/requirements.txt (line 3)) (1.1.4)
Requirement already satisfied: geopy==2.4.1 in /usr/local/lib/python3.13/dist-packages (from -r /content/requirements.txt (line 4)) (2.4.1)
Collecting lime==0.2.0.1 (from -r /content/requirements.txt (line 5))
  Downloading lime-0.2.0.1.tar.gz (275 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 275.7/275.7 kB 6.0 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: matplotlib==3.10.0 in /usr/local/lib/python3.13/dist-packages (from -r /content/requirements.txt (line 6)) (3.10.0)
Requirement already satisfied: mlxtend==0.23.4 in /usr/local/lib/python3.13/dist-packages (from -r /content/requirements.txt (line 7)) (0.23.4)
Requirement already satisfied: numpy==2.1.3 in /usr/local/lib/python3.13/dist-packages (from -r /content/requirements.txt (line 8)) (2.1.3)
Requirement already satisfied: pandas==2.2.3 in /usr/local/lib/python3.13/dist-packages (from -r /content/requirements.txt (line 9)) (2.2.3)
Collecting patsy==1.0.2 (from -r /content/requirements.txt (line 10))
  Downloading patsy-1.0.2-py2.py3-none-any.whl.metadata (3.6 kB)
Requirement already satisfied: plotly==5.24.1 in /usr/local/lib/python3.13/dist-packages (from -r /content/requirements.txt (line 11)) (5.24.1)
Requirement already satisfied: requests==2.32.4 in /usr/local/lib/python3.13/dist-packages (from -r /content/requirements.txt (line 12)) (2.32.4)
Collecting relativeImp==0.0.2 (from -r /content/requirements.txt (line 13))
  Downloading relativeImp-0.0.2-py3-none-any.whl.metadata (3.1 kB)
Requirement already satisfied: seaborn==0.13.2 in /usr/local/lib/python3.13/dist-packages (from -r /content/requirements.txt (line 14)) (0.13.2)
Requirement already satisfied: shap==0.52.0 in /usr/local/lib/python3.13/dist-packages (from -r /content/requirements.txt (line 15)) (0.52.0)
Requirement already satisfied: sklearn-compat==0.1.6 in /usr/local/lib/python3.13/dist-packages (from -r /content/requirements.txt (line 16)) (0.1.6)
Requirement already satisfied: sklearn-pandas==2.2.0 in /usr/local/lib/python3.13/dist-packages (from -r /content/requirements.txt (line 17)) (2.2.0)
Collecting statsmodels==0.14.6 (from -r /content/requirements.txt (line 18))
  Downloading statsmodels-0.14.6-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (9.5 kB)
Requirement already satisfied: torch==2.11.0 in /usr/local/lib/python3.13/dist-packages (from -r /content/requirements.txt (line 19)) (2.11.0+cpu)
Requirement already satisfied: uvicorn==0.52.4 in /usr/local/lib/python3.13/dist-packages (from -r /content/requirements.txt (line 20)) (0.52.4)
Requirement already satisfied: xgboost==3.4.1 in /usr/local/lib/python3.13/dist-packages (from -r /content/requirements.txt (line 21)) (3.4.1)
Collecting ydata-profiling==4.18.4 (from -r /content/requirements.txt (line 22))
  Downloading ydata_profiling-4.18.4-py2.py3-none-any.whl.metadata (23 kB)
Collecting networkx==3.3 (from -r /content/requirements.txt (line 23))
  Downloading networkx-3.3-py3-none-any.whl.metadata (5.1 kB)
Requirement already satisfied: starlette>=0.46.0 in /usr/local/lib/python3.13/dist-packages (from fastapi==0.141.1->-r /content/requirements.txt (line 1)) (1.6.0)
Requirement already satisfied: pydantic>=2.9.0 in /usr/local/lib/python3.13/dist-packages (from fastapi==0.141.1->-r /content/requirements.txt (line 1)) (2.13.5)
Requirement already satisfied: typing-extensions>=4.8.0 in /usr/local/lib/python3.13/dist-packages (from fastapi==0.141.1->-r /content/requirements.txt (line 1)) (4.16.0)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.13/dist-packages (from fastapi==0.141.1->-r /content/requirements.txt (line 1)) (0.4.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.13/dist-packages (from fastapi==0.141.1->-r /content/requirements.txt (line 1)) (0.0.5)
Requirement already satisfied: blinker>=1.9.0 in /usr/local/lib/python3.13/dist-packages (from Flask==3.1.3->-r /content/requirements.txt (line 2)) (1.9.0)
Requirement already satisfied: click>=8.1.3 in /usr/local/lib/python3.13/dist-packages (from Flask==3.1.3->-r /content/requirements.txt (line 2)) (8.5.0)
Requirement already satisfied: itsdangerous>=2.2.0 in /usr/local/lib/python3.13/dist-packages (from Flask==3.1.3->-r /content/requirements.txt (line 2)) (2.2.0)
Requirement already satisfied: jinja2>=3.1.2 in /usr/local/lib/python3.13/dist-packages (from Flask==3.1.3->-r /content/requirements.txt (line 2)) (3.1.6)
Requirement already satisfied: markupsafe>=2.1.1 in /usr/local/lib/python3.13/dist-packages (from Flask==3.1.3->-r /content/requirements.txt (line 2)) (3.0.3)
Requirement already satisfied: werkzeug>=3.1.0 in /usr/local/lib/python3.13/dist-packages (from Flask==3.1.3->-r /content/requirements.txt (line 2)) (3.1.8)
Requirement already satisfied: pyogrio>=0.7.2 in /usr/local/lib/python3.13/dist-packages (from geopandas==1.1.4->-r /content/requirements.txt (line 3)) (0.13.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.13/dist-packages (from geopandas==1.1.4->-r /content/requirements.txt (line 3)) (26.3)
Requirement already satisfied: pyproj>=3.5.0 in /usr/local/lib/python3.13/dist-packages (from geopandas==1.1.4->-r /content/requirements.txt (line 3)) (3.7.2)
Requirement already satisfied: shapely>=2.0.0 in /usr/local/lib/python3.13/dist-packages (from geopandas==1.1.4->-r /content/requirements.txt (line 3)) (2.1.2)
Requirement already satisfied: geographiclib<3,>=1.52 in /usr/local/lib/python3.13/dist-packages (from geopy==2.4.1->-r /content/requirements.txt (line 4)) (2.1)
Requirement already satisfied: scipy in /usr/local/lib/python3.13/dist-packages (from lime==0.2.0.1->-r /content/requirements.txt (line 5)) (1.16.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.13/dist-packages (from lime==0.2.0.1->-r /content/requirements.txt (line 5)) (4.67.3)
Requirement already satisfied: scikit-learn>=0.18 in /usr/local/lib/python3.13/dist-packages (from lime==0.2.0.1->-r /content/requirements.txt (line 5)) (1.6.1)
Requirement already satisfied: scikit-image>=0.12 in /usr/local/lib/python3.13/dist-packages (from lime==0.2.0.1->-r /content/requirements.txt (line 5)) (0.25.2)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib==3.10.0->-r /content/requirements.txt (line 6)) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.13/dist-packages (from matplotlib==3.10.0->-r /content/requirements.txt (line 6)) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.13/dist-packages (from matplotlib==3.10.0->-r /content/requirements.txt (line 6)) (4.64.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib==3.10.0->-r /content/requirements.txt (line 6)) (1.5.1)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.13/dist-packages (from matplotlib==3.10.0->-r /content/requirements.txt (line 6)) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib==3.10.0->-r /content/requirements.txt (line 6)) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.13/dist-packages (from matplotlib==3.10.0->-r /content/requirements.txt (line 6)) (2.9.0.post0)
Requirement already satisfied: joblib>=0.13.2 in /usr/local/lib/python3.13/dist-packages (from mlxtend==0.23.4->-r /content/requirements.txt (line 7)) (1.6.0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas==2.2.3->-r /content/requirements.txt (line 9)) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas==2.2.3->-r /content/requirements.txt (line 9)) (2026.3)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.13/dist-packages (from plotly==5.24.1->-r /content/requirements.txt (line 11)) (9.1.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests==2.32.4->-r /content/requirements.txt (line 12)) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.13/dist-packages (from requests==2.32.4->-r /content/requirements.txt (line 12)) (3.19)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.13/dist-packages (from requests==2.32.4->-r /content/requirements.txt (line 12)) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.13/dist-packages (from requests==2.32.4->-r /content/requirements.txt (line 12)) (2026.7.22)
Requirement already satisfied: slicer==0.0.8 in /usr/local/lib/python3.13/dist-packages (from shap==0.52.0->-r /content/requirements.txt (line 15)) (0.0.8)
Requirement already satisfied: numba in /usr/local/lib/python3.13/dist-packages (from shap==0.52.0->-r /content/requirements.txt (line 15)) (0.61.2)
Requirement already satisfied: llvmlite in /usr/local/lib/python3.13/dist-packages (from shap==0.52.0->-r /content/requirements.txt (line 15)) (0.44.0)
Requirement already satisfied: cloudpickle in /usr/local/lib/python3.13/dist-packages (from shap==0.52.0->-r /content/requirements.txt (line 15)) (3.1.2)
Requirement already satisfied: filelock in /usr/local/lib/python3.13/dist-packages (from torch==2.11.0->-r /content/requirements.txt (line 19)) (3.32.5)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.13/dist-packages (from torch==2.11.0->-r /content/requirements.txt (line 19)) (80.10.2)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.13/dist-packages (from torch==2.11.0->-r /content/requirements.txt (line 19)) (1.14.0)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.13/dist-packages (from torch==2.11.0->-r /content/requirements.txt (line 19)) (2025.12.0)
Requirement already satisfied: h11>=0.8 in /usr/local/lib/python3.13/dist-packages (from uvicorn==0.52.4->-r /content/requirements.txt (line 20)) (0.16.0)
Requirement already satisfied: nvidia-nccl-cu13 in /usr/local/lib/python3.13/dist-packages (from xgboost==3.4.1->-r /content/requirements.txt (line 21)) (2.31.2)
Requirement already satisfied: PyYAML<6.1,>=6.0.3 in /usr/local/lib/python3.13/dist-packages (from ydata-profiling==4.18.4->-r /content/requirements.txt (line 22)) (6.0.3)
Collecting visions<0.8.2,>=0.7.5 (from visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling==4.18.4->-r /content/requirements.txt (line 22))
  Downloading visions-0.8.1-py3-none-any.whl.metadata (11 kB)
Collecting minify-html>=0.15.0 (from ydata-profiling==4.18.4->-r /content/requirements.txt (line 22))
  Downloading minify_html-0.18.1-cp313-cp313-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (18 kB)
Collecting filetype>=1.0.0 (from ydata-profiling==4.18.4->-r /content/requirements.txt (line 22))
  Downloading filetype-1.2.0-py2.py3-none-any.whl.metadata (6.5 kB)
Collecting phik<0.13,>=0.12.5 (from ydata-profiling==4.18.4->-r /content/requirements.txt (line 22))
  Downloading phik-0.12.5-cp313-cp313-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (5.6 kB)
Collecting multimethod<2,>=1.4 (from ydata-profiling==4.18.4->-r /content/requirements.txt (line 22))
  Downloading multimethod-1.12-py3-none-any.whl.metadata (9.6 kB)
Requirement already satisfied: typeguard<5,>=4 in /usr/local/lib/python3.13/dist-packages (from ydata-profiling==4.18.4->-r /content/requirements.txt (line 22)) (4.6.0)
Collecting imagehash==4.3.2 (from ydata-profiling==4.18.4->-r /content/requirements.txt (line 22))
  Downloading ImageHash-4.3.2-py2.py3-none-any.whl.metadata (8.4 kB)
Requirement already satisfied: wordcloud>=1.9.4 in /usr/local/lib/python3.13/dist-packages (from ydata-profiling==4.18.4->-r /content/requirements.txt (line 22)) (1.9.6)
Collecting dacite<2,>=1.9 (from ydata-profiling==4.18.4->-r /content/requirements.txt (line 22))
  Downloading dacite-1.9.2-py3-none-any.whl.metadata (17 kB)
Requirement already satisfied: PyWavelets in /usr/local/lib/python3.13/dist-packages (from imagehash==4.3.2->ydata-profiling==4.18.4->-r /content/requirements.txt (line 22)) (1.9.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.13/dist-packages (from pydantic>=2.9.0->fastapi==0.141.1->-r /content/requirements.txt (line 1)) (0.8.0)
Requirement already satisfied: pydantic-core==2.46.5 in /usr/local/lib/python3.13/dist-packages (from pydantic>=2.9.0->fastapi==0.141.1->-r /content/requirements.txt (line 1)) (2.46.5)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.7->matplotlib==3.10.0->-r /content/requirements.txt (line 6)) (1.17.0)
Requirement already satisfied: imageio!=2.35.0,>=2.33 in /usr/local/lib/python3.13/dist-packages (from scikit-image>=0.12->lime==0.2.0.1->-r /content/requirements.txt (line 5)) (2.37.4)
Requirement already satisfied: tifffile>=2022.8.12 in /usr/local/lib/python3.13/dist-packages (from scikit-image>=0.12->lime==0.2.0.1->-r /content/requirements.txt (line 5)) (2026.8.23)
Requirement already satisfied: lazy-loader>=0.4 in /usr/local/lib/python3.13/dist-packages (from scikit-image>=0.12->lime==0.2.0.1->-r /content/requirements.txt (line 5)) (0.5)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.13/dist-packages (from scikit-learn>=0.18->lime==0.2.0.1->-r /content/requirements.txt (line 5)) (3.6.0)
Requirement already satisfied: anyio<5,>=3.6.2 in /usr/local/lib/python3.13/dist-packages (from starlette>=0.46.0->fastapi==0.141.1->-r /content/requirements.txt (line 1)) (4.14.2)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.13/dist-packages (from sympy>=1.13.3->torch==2.11.0->-r /content/requirements.txt (line 19)) (1.3.0)
Requirement already satisfied: attrs>=19.3.0 in /usr/local/lib/python3.13/dist-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling==4.18.4->-r /content/requirements.txt (line 22)) (26.1.0)
Collecting puremagic (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling==4.18.4->-r /content/requirements.txt (line 22))
  Downloading puremagic-2.2.0-py3-none-any.whl.metadata (7.3 kB)
Downloading patsy-1.0.2-py2.py3-none-any.whl (233 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 233.3/233.3 kB 17.0 MB/s eta 0:00:00
Downloading relativeImp-0.0.2-py3-none-any.whl (4.2 kB)
Downloading statsmodels-0.14.6-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (10.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.3/10.3 MB 82.4 MB/s eta 0:00:00
Downloading ydata_profiling-4.18.4-py2.py3-none-any.whl (400 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 400.8/400.8 kB 25.1 MB/s eta 0:00:00
Downloading networkx-3.3-py3-none-any.whl (1.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 64.8 MB/s eta 0:00:00
Downloading ImageHash-4.3.2-py2.py3-none-any.whl (296 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 296.7/296.7 kB 21.9 MB/s eta 0:00:00
Downloading dacite-1.9.2-py3-none-any.whl (16 kB)
Downloading filetype-1.2.0-py2.py3-none-any.whl (19 kB)
Downloading minify_html-0.18.1-cp313-cp313-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 86.6 MB/s eta 0:00:00
Downloading multimethod-1.12-py3-none-any.whl (10 kB)
Downloading phik-0.12.5-cp313-cp313-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (682 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 682.5/682.5 kB 36.5 MB/s eta 0:00:00
Downloading visions-0.8.1-py3-none-any.whl (105 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 105.4/105.4 kB 7.6 MB/s eta 0:00:00
Downloading puremagic-2.2.0-py3-none-any.whl (71 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 72.0/72.0 kB 5.2 MB/s eta 0:00:00
Building wheels for collected packages: lime
  Building wheel for lime (setup.py) ... done
  Created wheel for lime: filename=lime-0.2.0.1-py3-none-any.whl size=283913 sha256=0c31dcbcc1c5c839e7f33b80e395c7c85a21b43f6cf43898330e7b9021faf79d
  Stored in directory: /root/.cache/pip/wheels/7c/04/5c/157dc9106512a6c7a30653ec064490c94a49e0fc8f63d19ab9
Successfully built lime
Installing collected packages: minify-html, filetype, puremagic, patsy, networkx, multimethod, dacite, imagehash, visions, statsmodels, relativeImp, phik, lime, ydata-profiling
  Attempting uninstall: patsy
    Found existing installation: patsy 1.0.3
    Uninstalling patsy-1.0.3:
      Successfully uninstalled patsy-1.0.3
  Attempting uninstall: networkx
    Found existing installation: networkx 3.6.1
    Uninstalling networkx-3.6.1:
      Successfully uninstalled networkx-3.6.1
  Attempting uninstall: statsmodels
    Found existing installation: statsmodels 0.15.0
    Uninstalling statsmodels-0.15.0:
      Successfully uninstalled statsmodels-0.15.0
Successfully installed dacite-1.9.2 filetype-1.2.0 imagehash-4.3.2 lime-0.2.0.1 minify-html-0.18.1 multimethod-1.12 networkx-3.3 patsy-1.0.2 phik-0.12.5 puremagic-2.2.0 relativeImp-0.0.2 statsmodels-0.14.6 visions-0.8.1 ydata-profiling-4.18.4

In [13]:
# Librerias
import warnings
warnings.filterwarnings('ignore')
import pandas as pd
import numpy as np
import sys
import re
import patsy
import ast
from pathlib import Path
from sklearn.model_selection import train_test_split, cross_val_score, RepeatedKFold
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression, LogisticRegression, Ridge, Lasso
from sklearn import metrics
from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor, GradientBoostingRegressor
from xgboost import XGBRegressor
from sklearn.model_selection import RandomizedSearchCV
import xgboost as xgb
import torch
import torch.nn as nn
from relativeImp import relativeImp
from  ydata_profiling import ProfileReport
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer
from scipy.stats import chi2_contingency
import geopandas as gpd
import pickle
import sklearn.impute as skl_imp
from sklearn.metrics import mean_squared_error, r2_score, accuracy_score, mean_absolute_error, median_absolute_error, f1_score, roc_auc_score, roc_curve

In [3]:
# Funciones
execfile("/content/FuncionesTFM.py")
execfile("/content/Pipeline_limpieza_data.py")
execfile("/content/geo_barcelona.geojson")

In [4]:
# Data a procesar para predecir
data = pd.read_csv('/content/airbnb_junio.csv')

In [5]:
#Obtener la data procesada
geo = gpd.read_file("geo_barcelona.geojson").to_crs(25831)
data_limpia = preparar_limpieza(data)

In [6]:
# Leo  nuestro modelo json
from xgboost import XGBRegressor

model = XGBRegressor()
model.load_model("/content/modelo_xgb.json")

In [7]:
# SELECCIÓN DE VARIABLES
variables_modelo = list(model.feature_names_in_)
X_final = data_limpia[variables_modelo].astype(float)

#  PREDICCIÓN
pred = model.predict(X_final)

In [8]:
prediccion = pd.DataFrame(pred)
prediccion.columns = ['pred_precio_log']

In [9]:
prediccion.head()

   pred_precio_log
0         5.954765
1         5.951742
2         6.017750
3         3.621529
4         5.251431

In [10]:

prediccion['precio_pred'] = np.exp(prediccion['pred_precio_log'])
prediccion['precio_pred'] = prediccion['precio_pred'].round(2)

In [11]:
prediccion

       pred_precio_log  precio_pred
0             5.954765   385.589996
1             5.951742   384.420013
2             6.017750   410.649994
3             3.621529    37.389999
4             5.251431   190.839996
...                ...          ...
13350         4.245271    69.769997
13351         4.245271    69.769997
13352         5.893930   362.829987
13353         5.902063   365.790009
13354         5.859904   350.690002

[13355 rows x 2 columns]

In [14]:
# Evaluar la predicción con los datos de junio
y_junio = data_limpia['price_log']
r2_junio = r2_score(y_junio, prediccion['pred_precio_log'])
rmse_junio = np.sqrt(mean_squared_error(y_junio, prediccion['pred_precio_log']))
y_junio_euros = np.exp(y_junio)
pred_junio_euros = np.exp(prediccion['pred_precio_log'])
mae_junio = mean_absolute_error(y_junio_euros, pred_junio_euros)
mediana_junio = median_absolute_error(y_junio_euros, pred_junio_euros)

print(f"R² junio: {r2_junio:.4f}")
print(f"RMSE junio: {rmse_junio:.4f}")
print(f"MAE junio: {mae_junio:.2f}")
print(f"Mediana del error junio: {mediana_junio:.2f}")

R² junio: 0.8747
RMSE junio: 0.3082
MAE junio: 56.82
Mediana del error junio: 23.97

In [15]:
# Guardamos  la prediccion junio
prediccion = prediccion.join(data_limpia[['id']])
prediccion.to_csv('prediccion_junio.csv', index=False)
prediccion

       pred_precio_log  precio_pred                   id
0             5.954765   385.589996                18674
1             5.951742   384.420013                23197
2             6.017750   410.649994                34981
3             3.621529    37.389999                36763
4             5.251431   190.839996                40983
...                ...          ...                  ...
13350         4.245271    69.769997  1714453367636295798
13351         4.245271    69.769997  1714507108958061169
13352         5.893930   362.829987  1714524223290226460
13353         5.902063   365.790009  1714528494413566181
13354         5.859904   350.690002  1714531569719409706

[13355 rows x 3 columns]